repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
      exclude: "(data/|\\.github/db_sources/)"
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: "(data/|\\.github/db_sources/)"
    - id: mixed-line-ending
      args: [--fix=lf]
      exclude: "(data/|\\.github/db_sources/)"
    - id: requirements-txt-fixer
    - id: check-yaml
      args: [--unsafe]
    - id: check-toml

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.30
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.9.6'
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      types_or: [python, jupyter]
    - id: ruff-format
      types_or: [python, jupyter]

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: uv run mypy --config-file pyproject.toml
      language: system
      types: [python]
      exclude: "tests"

  - repo: https://github.com/crate-ci/typos
    rev: v1.30.2
    hooks:
      - id: typos
        args: []
        exclude: "(data/|\\.github/db_sources/)"

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
    - id: nbqa-ruff
      args: [--fix, --exit-non-zero-on-fix]

ci:
    autofix_commit_msg: |
        [pre-commit.ci] Add auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: [pytest,doctest,mypy]
    submodules: false
